#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Embed plugin kernel sources into a C++ translation unit for NVRTC."""

import argparse
import os
from collections import namedtuple
from pathlib import Path

Entry = namedtuple('Entry', ['input_path', 'include_name', 'var_name'])

XQA_FILES = [
    'mha.cu',
    'mha.h',
    'mha_components.cuh',
    'mha_stdheaders.cuh',
    'mhaUtils.cuh',
    'barriers.cuh',
    'cuda_hint.cuh',
    'defines.h',
    'ldgsts.cuh',
    'mma.cuh',
    'platform.h',
    'specDec.h',
    'utils.cuh',
    'utils.h',
]

XQA_MAIN_SOURCE = 'mha.cu'
BLACKWELL_GEMV_MAIN_SOURCE = 'nvfp4A16BlackwellGemv.cu'

PROJECT_HEADERS = [
    'common/cudaMacros.h',
    'kernels/decodeAttentionKernels/xqaKernelTypes.h',
]

REQUIRED_CUDA_HEADERS = [
    'cuda_bf16.h',
    'cuda_bf16.hpp',
    'cuda_fp16.h',
    'cuda_fp16.hpp',
]

OPTIONAL_CUDA_HEADERS = [
    'cuda_fp8.h',
    'cuda_fp8.hpp',
    'cuda_fp4.h',
    'cuda_fp4.hpp',
    'cuda_fp6.h',
    'cuda_fp6.hpp',
]

PROLOGUE = '''// Auto-generated by kernelSrcs/jit_utils/gen_cpp_header.py -- do not edit.
#include "kernels/PluginJitKernels/pluginJitEmbeddedSources.h"

#include <stdexcept>

namespace trt_edgellm
{
namespace
{

'''

EPILOGUE = '''} // namespace trt_edgellm
'''


def to_identifier(name):
    return ''.join(c if c.isalnum() else '_' for c in name)


def to_raw_string_literal(content, path):
    for delimiter in ('plugin_jit_embed', 'plugin_jit_embed2',
                      'plugin_jit_embed3'):
        if ')' + delimiter not in content:
            return 'R"{d}({c}){d}"'.format(d=delimiter, c=content)
    raise RuntimeError(
        '{}: content collides with every raw string delimiter'.format(path))


def collect_entries(xqa_dir, gemv_dir, cpp_dir, cuda_include_dir):
    entries = []
    for name in XQA_FILES:
        entries.append(
            Entry(input_path=os.path.join(xqa_dir, name),
                  include_name=name,
                  var_name='kSrc_' + to_identifier(name)))

    entries.append(
        Entry(input_path=os.path.join(gemv_dir,
                                      BLACKWELL_GEMV_MAIN_SOURCE),
              include_name=BLACKWELL_GEMV_MAIN_SOURCE,
              var_name='kSrc_' + to_identifier(BLACKWELL_GEMV_MAIN_SOURCE)))

    for rel_path in PROJECT_HEADERS:
        entries.append(
            Entry(input_path=os.path.join(cpp_dir, rel_path),
                  include_name=rel_path,
                  var_name='kSrc_' + to_identifier(rel_path)))

    for name in REQUIRED_CUDA_HEADERS:
        entries.append(
            Entry(input_path=os.path.join(cuda_include_dir, name),
                  include_name=name,
                  var_name='kSrc_cuda_' + to_identifier(name)))

    for name in OPTIONAL_CUDA_HEADERS:
        path = os.path.join(cuda_include_dir, name)
        if not os.path.exists(path):
            print('note: optional CUDA header not present, skipping: ' + path)
            continue
        entries.append(
            Entry(input_path=path,
                  include_name=name,
                  var_name='kSrc_cuda_' + to_identifier(name)))

    missing = [
        entry.input_path for entry in entries
        if not os.path.exists(entry.input_path)
    ]
    if missing:
        raise SystemExit('error: embedded source(s) not found:\n  ' +
                         '\n  '.join(missing))
    return entries


def generate(entries):
    out = [PROLOGUE]
    main_vars = {}
    source_vars = {}

    for entry in entries:
        if entry.include_name in source_vars:
            raise SystemExit('error: duplicate embedded include name {}'.format(
                entry.include_name))
        content = Path(entry.input_path).read_text()
        out.append('static char const {}[] = {};\n\n'.format(
            entry.var_name,
            to_raw_string_literal(content, entry.input_path)))
        if entry.include_name in (XQA_MAIN_SOURCE,
                                  BLACKWELL_GEMV_MAIN_SOURCE):
            main_vars[entry.include_name] = entry.var_name
        source_vars[entry.include_name] = entry.var_name

    for main_source in (XQA_MAIN_SOURCE, BLACKWELL_GEMV_MAIN_SOURCE):
        if main_source not in main_vars:
            raise SystemExit(
                'error: main source {} was not embedded'.format(main_source))

    out.append('} // namespace\n\n')
    cuda_headers = [
        name for name in REQUIRED_CUDA_HEADERS + OPTIONAL_CUDA_HEADERS
        if name in source_vars
    ]
    xqa_headers = ([
        name for name in XQA_FILES if name != XQA_MAIN_SOURCE
    ] + PROJECT_HEADERS + cuda_headers)

    out.append('PluginJitEmbeddedSources const& getPluginJitEmbeddedSources(\n')
    out.append('    PluginJitProgram const program)\n{\n')
    out.append('    static PluginJitEmbeddedSources const sXqaSources{\n')
    out.append('        "{}",\n'.format(XQA_MAIN_SOURCE))
    out.append('        {},\n'.format(main_vars[XQA_MAIN_SOURCE]))
    out.append('        {\n')
    for name in xqa_headers:
        out.append('            {{"{}", {}}},\n'.format(
            name, source_vars[name]))
    out.append('        }};\n')
    out.append(
        '    static PluginJitEmbeddedSources const sBlackwellGemvSources{\n')
    out.append('        "{}",\n'.format(BLACKWELL_GEMV_MAIN_SOURCE))
    out.append('        {},\n'.format(
        main_vars[BLACKWELL_GEMV_MAIN_SOURCE]))
    out.append('        {\n')
    for name in cuda_headers:
        out.append('            {{"{}", {}}},\n'.format(
            name, source_vars[name]))
    out.append('        }};\n\n')
    out.append('    PluginJitEmbeddedSources const* result{};\n')
    out.append('    switch (program)\n    {\n')
    out.append('    case PluginJitProgram::kXQA: result = &sXqaSources; break;\n')
    out.append('    case PluginJitProgram::kNVFP4_A16_BLACKWELL_GEMV:\n')
    out.append('        result = &sBlackwellGemvSources;\n')
    out.append('        break;\n')
    out.append('    }\n')
    out.append('    if (result == nullptr)\n    {\n')
    out.append('        throw std::invalid_argument("Unknown plugin JIT program");\n')
    out.append('    }\n')
    out.append('    return *result;\n')
    out.append('}\n\n')
    out.append(EPILOGUE)
    return ''.join(out)


def main():
    parser = argparse.ArgumentParser(
        description='Embed plugin kernel sources into a C++ TU for NVRTC.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-o', '--output', required=True)
    parser.add_argument('--xqa_dir', required=True)
    parser.add_argument('--gemv_dir', required=True)
    parser.add_argument('--cpp_dir', required=True)
    parser.add_argument('--cuda_include_dir', required=True)
    args = parser.parse_args()

    content = generate(
        collect_entries(args.xqa_dir, args.gemv_dir, args.cpp_dir,
                        args.cuda_include_dir))
    output = Path(args.output)
    if output.exists() and output.read_text() == content:
        print('{} is up to date'.format(output))
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(output.name + '.tmp{}'.format(os.getpid()))
    tmp.write_text(content)
    os.replace(str(tmp), str(output))
    print('Generated {}'.format(output))


if __name__ == '__main__':
    main()
