/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "multimodal/common/multimodalRunner.h"
#include <array>
#include <common/tensor.h>
#include <cuda_fp16.h>
#include <utility>
#include <vector>

namespace trt_edgellm
{
namespace rt
{

//! \brief Configuration for Nemotron-Omni RADIO vision encoder
struct NemotronOmniViTConfig
{
    int64_t maxNumBlocks{0};    //!< Maximum number of image tiles / video tubelets (across the batch)
    int64_t minNumBlocks{0};    //!< Minimum number of image tiles (across the batch)
    int64_t numChannels{3};     //!< Number of image channels (RGB)
    int64_t outHiddenSize{0};   //!< Output hidden dimension (LLM hidden size)
    int64_t blockImageSizeH{0}; //!< Image height per tile (preferred_resolution)
    int64_t blockImageSizeW{0}; //!< Image width per tile (preferred_resolution)

    int64_t tokensPerBlock{256}; //!< Tokens per tile after pixel shuffle

    int64_t vitHiddenSize{0};   //!< ViT hidden dimension (embedder GEMM output)
    int64_t patchSize{16};      //!< ViT patch size
    int64_t maxNumPatches{0};   //!< Max patches per block (engine profile)
    int64_t downsampleScale{2}; //!< Pixel-shuffle downsample factor (1/downsample_ratio)

    int64_t videoTemporalPatchSize{2};   //!< Frames packed per video tubelet (T)
    int64_t videoTargetNumPatches{1024}; //!< Patch budget per video frame (aspect-preserving resize)
    bool videoMaintainAspectRatio{true}; //!< Aspect-preserving video frame resize
    float videoPruningRate{0.0F};        //!< EVS pruning rate q (0 disables pruning)

    int32_t vocabSize{0};          //!< Vocabulary size (image token ID offset)
    int32_t imgContextTokenId{18}; //!< Image context token ID
    int32_t imgStartTokenId{0};    //!< Image start token ID
    int32_t imgEndTokenId{0};      //!< Image end token ID

    std::array<float, 3> imageMean{{0.5F, 0.5F, 0.5F}}; //!< Image normalization mean
    std::array<float, 3> imageStd{{0.5F, 0.5F, 0.5F}};  //!< Image normalization std

    int64_t minImageTokensPerImage{0}; //!< Minimum image tokens generated by each image. Used for resizing.
    int64_t maxImageTokensPerImage{0}; //!< Maximum image tokens generated by each image. Used for resizing.
};

//! \brief Runner for the Nemotron-Omni RADIO vision encoder (images + video)
//!
//! The engine consumes patch embeddings, not pixels: the embedder GEMM (CuTe DSL) + pos-embed add run
//! here, with image/video embedder weights from the nemotron_omni_embedder.safetensors weight file. Video
//! packs T-frame tubelets and EVS-prunes tokens in preprocess() (per-tubelet counts feed text expansion).
class NemotronOmniViTRunner : public MultimodalRunner
{
public:
    //! \brief Constructor for NemotronOmniViTRunner
    //! \param[in] engineDir Directory containing the TensorRT engine files
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if engineDir does not contain valid engine files
    //! \throws std::runtime_error if buffer allocation fails
    //! \throws std::runtime_error if a CUDA error occurs
    NemotronOmniViTRunner(std::string const& engineDir, cudaStream_t stream);

    ~NemotronOmniViTRunner() noexcept = default;

    //! \brief Preprocess multimodal input including images and text
    //! \param[in] request LLM generation request containing images and text
    //! \param[in,out] batchedInputIds Batched input token IDs after preprocessing
    //! \param[in] tokenizer Tokenizer for text processing
    //! \param[in,out] mropeCosSinOut MRoPE cos/sin output tensor (unused by this model)
    //! \param[in] stream CUDA stream for execution
    //! \return True if preprocessing succeeded, false otherwise
    bool preprocess(rt::LLMGenerationRequest const& request, std::vector<std::vector<int32_t>>& batchedInputIds,
        tokenizer::Tokenizer const* tokenizer, [[maybe_unused]] rt::OptionalOutputTensor mropeCosSinOut,
        cudaStream_t stream, bool imageOnly = false, bool skipEncoderWork = false) override;

    //! \brief Run inference on the vision encoder
    //! \param[in] stream CUDA stream for execution
    //! \return True if inference succeeded, false otherwise
    bool infer(cudaStream_t stream) noexcept override;

    //! \brief Validate and load configuration from JSON file
    //! \param[in] engineDir Path to engine directory
    //! \return True if configuration is valid and loaded successfully, false otherwise
    bool validateAndFillConfig(std::string const& engineDir) override;

    //! \brief Allocate buffers for inference
    //! \param[in] stream CUDA stream for execution
    //! \return True if allocation succeeded, false otherwise
    //! \throws std::runtime_error if a CUDA error occurs
    bool allocateBuffer(cudaStream_t stream) override;

private:
    //! \brief Preprocess all images in the request using dynamic tiling and thumbnail
    //! \param[in] request LLM generation request containing images
    //! \param[out] imageTokenLengths Token lengths for each image
    //! \param[out] numImages Number of images per request
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if image size is unexpected, or number of blocks is excessive
    void imagePreprocess(rt::LLMGenerationRequest const& request, std::vector<int64_t>& imageTokenLengths,
        std::vector<int64_t>& numImages, cudaStream_t stream);
    void imagePreprocessTokenLengthsOnly(rt::LLMGenerationRequest const& request,
        std::vector<int64_t>& imageTokenLengths, std::vector<int64_t>& numImages);

    //! \brief Preprocess a video frame stack and run the visual engine
    //!
    //! Runs resize, tubelet packing, embedder GEMM, engine inference and EVS
    //! pruning. Runs inside preprocess() because the per-tubelet retained
    //! token counts (EVS output) are needed for text placeholder expansion.
    //!
    //! \param[in] request LLM generation request containing exactly one video and no images
    //! \param[out] imageTokenLengths Retained token count per video tubelet
    //! \param[out] numImages Number of visual items (tubelets) per request
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error on malformed input or engine failure
    void videoPreprocess(rt::LLMGenerationRequest const& request, std::vector<int64_t>& imageTokenLengths,
        std::vector<int64_t>& numImages, cudaStream_t stream);

    //! \brief Format and process a single image patch
    //! \param[in] image Input image data
    //! \param[out] imageTokenLengths Token lengths for each image
    //! \param[out] numImages Number of images processed
    //! \param[out] totalNumBlocks Total number of image blocks
    //! \param[in] isThumbnail Whether the image is a thumbnail
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if image size is unexpected, or number of blocks is excessive
    void formatPatch(rt::imageUtils::ImageData const& image, std::vector<int64_t>& imageTokenLengths,
        int64_t& numImages, int64_t& totalNumBlocks, bool isThumbnail, cudaStream_t stream);

    //! \brief Preprocess text portion of the request
    //! \param[in] request LLM generation request
    //! \param[in,out] batchInputIds Batch of input token IDs
    //! \param[in] numImages Number of images per request
    //! \param[in] imageTokenLengths Token lengths for each image
    //! \param[in] tokenizer Tokenizer for text processing
    void textPreprocess(rt::LLMGenerationRequest const& request, std::vector<std::vector<int32_t>>& batchInputIds,
        std::vector<int64_t> const& numImages, std::vector<int64_t> const& imageTokenLengths,
        trt_edgellm::tokenizer::Tokenizer const* tokenizer);

    //! \brief Load embedder GEMM weights and raw pos_embed from the safetensors weight file
    //! \param[in] stream CUDA stream for execution
    //! \return True on success
    bool loadVEmbedder(cudaStream_t stream);

    //! \brief Run the patch embedder stage: patchify + CuTe DSL GEMM + pos_embed add
    //! \param[in] numGroups Number of blocks / tubelets (GEMM batch rows / numPatches)
    //! \param[in] numPatches Patches per block for the current grid
    //! \param[in] temporalPatchSize Frames packed per row (1 for images)
    //! \param[in] posEmbed Device position embedding [numPatches, vitHidden]
    //! \param[in] weight Device embedder weight [vitHidden, temporalPatchSize*3*P*P]
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if the GEMM cannot run on this device
    void runEmbedderStage(int64_t numGroups, int64_t numPatches, int64_t temporalPatchSize, rt::Tensor const& posEmbed,
        rt::Tensor const& weight, cudaStream_t stream);

    //! \brief Bilinearly interpolate the raw pos_embed to a (gridH, gridW) patch grid (host, FP32 math)
    //! \param[in] gridH Target grid height in patches
    //! \param[in] gridW Target grid width in patches
    //! \return Host FP16 buffer [gridH*gridW * vitHidden]
    std::vector<half> interpolatePosEmbedHost(int64_t gridH, int64_t gridW) const;

    //! \brief Build pixel-shuffle gather indices for a (gridH, gridW) patch grid
    //! \param[in] gridH Grid height in patches
    //! \param[in] gridW Grid width in patches
    //! \return Host row-major table [gridH*gridW/scale^2, scale^2]
    std::vector<int64_t> buildShuffleIndicesHost(int64_t gridH, int64_t gridW) const;

    //! \brief Upload a shuffle-index table and set the engine input shapes for one enqueue
    //! \param[in] numBlocks Number of blocks / tubelets
    //! \param[in] gridH Grid height in patches
    //! \param[in] gridW Grid width in patches
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if shapes cannot be bound
    void bindEngineShapes(int64_t numBlocks, int64_t gridH, int64_t gridW, cudaStream_t stream);

    //! \brief Aspect-preserving video frame patch-grid selection
    //! \param[in] width Source frame width in pixels
    //! \param[in] height Source frame height in pixels
    //! \return {gridW, gridH} in patches (each a multiple of downsampleScale)
    std::pair<int64_t, int64_t> computeVideoTargetPatches(int64_t width, int64_t height) const;

    //! \brief Build the token ids that replace the single video marker
    //!
    //! One "<img>{imgContextTokenId x count}</img>" group per tubelet, prefixed by the
    //! per-frame source-timestamp label and newline-joined (HF/vLLM Frame-label layout).
    //! Uses mVideoTimestamps and mVideoTubeletCounts populated by videoPreprocess().
    //!
    //! \param[in] tokenizer Tokenizer for the label / marker text
    //! \return Token ids for the expanded video placeholder
    std::vector<int32_t> buildVideoPlaceholderIds(trt_edgellm::tokenizer::Tokenizer const* tokenizer) const;

    NemotronOmniViTConfig mConfig;                 //!< Nemotron-Omni RADIO ViT configuration
    std::string mEngineDir{};                      //!< Engine directory (embedder weights)
    rt::Tensor mVitInput{};                        //!< Engine input: patch embeddings [B, N, vitHidden]
    rt::Tensor mShuffleIndices{};                  //!< Engine input: pixel-shuffle gather indices [N/s^2, s^2]
    rt::Tensor mBlockPixels{};                     //!< Normalized CHW pixel staging [frames, 3, H, W]
    rt::Tensor mGemmRows{};                        //!< Patchified GEMM input rows [B*N, T*3*P*P]
    rt::Tensor mImageEmbedderWeight{};             //!< Image embedder GEMM weight [vitHidden, 3*P*P]
    rt::Tensor mVideoEmbedderWeight{};             //!< Video embedder GEMM weight [vitHidden, T*3*P*P]
    rt::Tensor mPosEmbedImage{};                   //!< Position embedding for the square image grid
    rt::Tensor mPosEmbedGrid{};                    //!< Position embedding scratch for video grids
    rt::Tensor mEvsScores{};                       //!< EVS dissimilarity scores [maxTokens] (device)
    rt::Tensor mEvsGatherIdx{};                    //!< EVS retained-row indices [maxTokens] (device)
    rt::Tensor mEvsScratch{};                      //!< EVS row-compaction scratch [maxTokens, outHidden]
    rt::Tensor mImageMean{};                       //!< Image mean tensor
    rt::Tensor mImageStd{};                        //!< Image standard deviation tensor
    rt::Tensor mImageDevice{};                     //!< Temporary image buffer for preprocessing
    rt::Tensor mNormalizedImageDevice{};           //!< Temporary normalized image buffer
    rt::Tensor mRawImageDevice{};                  //!< Raw (pre-resize) image device buffer for the GPU resize
    rt::Tensor mResizeTmpDevice{};                 //!< Float scratch (horizontal pass) for the GPU resize
    rt::imageUtils::ImageData mResizedImageHost{}; //!< Pinned host buffer for the video CPU resize
    std::vector<float> mPosEmbedRawHost{};         //!< Raw max-resolution pos_embed (host, FP32)
    int64_t mPosEmbedRawSide{0};                   //!< Raw pos_embed grid side (e.g. 128)
    std::vector<int64_t> mImageShuffleTable{};     //!< Cached shuffle indices for the square image grid
    rt::Tensor mShuffleIndicesHost{};              //!< Pinned host staging for the shuffle-index H2D
    rt::Tensor mEvsGatherIdxHost{};                //!< Pinned host staging for the EVS gather-index H2D
    rt::Tensor mEvsScoresHost{};                   //!< Pinned host staging for the EVS score D2H
    rt::Tensor mPosEmbedGridHost{};                //!< Pinned host staging for the pos-embed H2D (image + video)
    bool mHasVideoEmbedder{false};                 //!< Weight file carries video_embedder weights
    int64_t mTotalNumBlocks{0};                    //!< Total blocks preprocessed (for batched infer)
    bool mRequestHasVideo{false};                  //!< Current request carries a video (vs image tiles)
    std::vector<int64_t> mVideoTubeletCounts{};    //!< Retained token count per video tubelet (EVS output)
    std::vector<double> mVideoTimestamps{};        //!< Source timestamps (s) of the sampled video frames
};

} // namespace rt
} // namespace trt_edgellm
